# Generated by Django 6.1.1 on 2026-10-04 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(blank=True, help_text='Генерируется автоматически. Например: PAT-2026-A3F8B1', max_length=50, unique=True, verbose_name='Код пациента')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('CHEST_XRAY', 'Рентгенограмма грудной клетки'), ('FLG', 'ФЛГ'), ('CHEST_CT', 'КТ органов грудной клетки'), ('BRAIN_CT', 'КТ головного мозга'), ('MAMMO', 'Маммограмма')], max_length=20, verbose_name='Тип исследования')),
                ('study_date', models.DateField(verbose_name='Дата исследования')),
                ('radiologist_conclusion', models.TextField(help_text='Текст, который написал врач-рентгенолог', verbose_name='Заключение рентгенолога')),
                ('file', models.FileField(blank=True, null=True, upload_to='studies/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('new', 'Новое — ждёт обработки ИИ'), ('ai_done', 'ИИ обработал — ждёт врача'), ('in_review', 'Врач проверяет'), ('approved', 'План утверждён'), ('sent', 'Отправлено пациенту')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='core.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'ИИ'), ('doctor', 'Врач')], default='ai', max_length=10, verbose_name='Источник')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрена'), ('edited', 'Изменена врачом'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('specialist', models.CharField(max_length=100, verbose_name='Специалист')),
                ('specialty_code', models.CharField(blank=True, max_length=50, verbose_name='Код специальности')),
                ('reasoning', models.TextField(verbose_name='Обоснование')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Уверенность ИИ')),
                ('original_specialist', models.CharField(blank=True, max_length=100)),
                ('original_reasoning', models.TextField(blank=True)),
                ('original_priority', models.CharField(blank=True, max_length=10)),
                ('doctor_comment', models.TextField(blank=True, verbose_name='Комментарий врача')),
                ('raw_model_output', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверил врач')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.study', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['-priority', 'specialist'],
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations_snapshot', models.JSONField(default=list, verbose_name='Снимок рекомендаций')),
                ('doctor_comment', models.TextField(blank=True, verbose_name='Комментарий врача')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('sent', 'Отправлен пациенту')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Утвердил врач')),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='core.study', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'План обращения',
                'verbose_name_plural': 'Планы обращения',
            },
        ),
    ]
