# Generated by Django 6.1.1 on 2026-10-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='original_priority',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='original_reasoning',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='original_specialist',
        ),
    ]
