# Generated by Django 6.1.1 on 2026-10-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='modality',
            field=models.CharField(choices=[('CHEST_XRAY', 'Рентгенограмма грудной клетки'), ('FLG', 'ФЛГ'), ('CHEST_CT', 'КТ органов грудной клетки'), ('BRAIN_CT', 'КТ головного мозга'), ('MAMMO', 'Маммограмма')], max_length=20, verbose_name='Тип исследования'),
        ),
    ]
