# Generated by Django 6.1.1 on 2026-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_recommendation_original_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('processing', 'ИИ обрабатывает'), ('ai_done', 'ИИ обработал — ждёт врача'), ('in_review', 'Врач проверяет'), ('approved', 'План утверждён'), ('sent', 'Отправлено пациенту')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
