# Generated by Django 6.1.1 on 2026-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_study_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, help_text='Например: PAT-2026-0001', max_length=50, null=True, verbose_name='Анонимный код пациента'),
        ),
    ]
