# Generated by Django 6.1.1 on 2026-10-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_study_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='doctor_comment',
        ),
    ]
