# Generated by Django 6.1.1 on 2026-10-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recommendation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'План обращения', 'verbose_name_plural': 'Планы обращения'},
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='careplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
