# Generated by Django 6.1.1 on 2026-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_careplan_options_remove_careplan_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careplan',
            name='recommendations_snapshot',
            field=models.JSONField(default=list, verbose_name='Рекомендации'),
        ),
    ]
