# Generated by Django 6.1.1 on 2026-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_careplan_recommendations_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='radiologist_conclusion',
            field=models.TextField(help_text='Заключение, сформированное платформой «Третье Мнение»', verbose_name='Заключение платформы «Третье Мнение»'),
        ),
    ]
