# Generated by Django 6.1.1 on 2026-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_study_radiologist_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='slices_count',
            field=models.PositiveIntegerField(blank=True, help_text='Для КТ и МРТ — количество срезов в серии. Оставьте пустым, если неизвестно.', null=True, verbose_name='Количество срезов'),
        ),
        migrations.AddField(
            model_name='study',
            name='title',
            field=models.CharField(blank=True, help_text='Краткое название для списка. Например: "Очаг в легком", "Коронарный кальциноз". Если пусто — берётся первая строка заключения.', max_length=200, verbose_name='Название исследования'),
        ),
    ]
